[package]
name = "dsec-apiserver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dsec-rpc.workspace = true
dsec-iam.workspace = true
dsec-watcher.workspace = true
dsec-placement.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile.workspace = true
dsec-edge.workspace = true
dsec-aether.workspace = true
