[workspace]
resolver = "2"
members = [
    "crates/rpc",
    "crates/apiserver",
    "crates/iam",
    "crates/placement",
    "crates/watcher",
    "crates/edge",
    "crates/aether",
    "crates/chronus",
    "crates/trajlog",
    "crates/vmm",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "time", "process", "fs", "signal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
libc = "0.2"
tempfile = "3"
dsec-rpc = { path = "crates/rpc" }
dsec-iam = { path = "crates/iam" }
dsec-watcher = { path = "crates/watcher" }
dsec-placement = { path = "crates/placement" }
dsec-edge = { path = "crates/edge" }
dsec-aether = { path = "crates/aether" }
dsec-chronus = { path = "crates/chronus" }
dsec-trajlog = { path = "crates/trajlog" }
dsec-apiserver = { path = "crates/apiserver" }
