//! Trajectory log: a globally ordered, durable record of every command
//! invocation and its result, one log per sandbox (V4 §5.2.5).
//!
//! Serves three purposes, as in DSec: (1) *client fast-forwarding* — after a
//! client is preempted and resumes, a re-issued operation that already
//! completed returns its cached result instead of re-executing (which the
//! paper notes also prevents errors from re-running non-idempotent commands);
//! (2) *provenance* — every state change records who ran what, when, and with
//! what outcome; (3) *deterministic replay* — the ordered entries are enough
//! to reproduce a historical session.
//!
//! Identity of an operation for fast-forward: (sandbox, terminal session,
//! client-side index). A re-issued operation with the same identity and the
//! same argument matches; the same identity with a *different* argument is a
//! divergence and is reported rather than silently replayed.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Mutex;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Entry {
    /// Per-sandbox monotonic sequence number: the global order (V4 §5.2.5).
    pub seq: u64,
    pub ts_ms: u64,
    /// Sandbox owner (principal) recorded at create time: provenance.
    pub user: String,
    /// Terminal-session id chosen by the client (P §3.1).
    pub session: String,
    /// Client-side position within the session; the fast-forward key.
    pub idx: u64,
    /// Operation name: "exec", "read_file", ...
    pub op: String,
    /// Operation arguments as sent.
    pub params: serde_json::Value,
    /// Captured outcome (stdout/stderr/exit code, ...). `None` while the
    /// operation is in flight; a completed entry always has one.
    pub result: serde_json::Value,
}

pub struct TrajLog {
    dir: PathBuf,
    /// sandbox -> (next seq, cached entries by (session, idx))
    state: Mutex<HashMap<String, Log>>,
}

struct Log {
    next_seq: u64,
    by_key: HashMap<(String, u64), Entry>,
}

impl TrajLog {
    /// Open (or create) the log directory. Existing per-sandbox files are
    /// reloaded, so the fast-forward cache survives an edge restart.
    pub fn open(dir: impl Into<PathBuf>) -> Result<TrajLog> {
        let dir = dir.into();
        std::fs::create_dir_all(&dir).with_context(|| dir.display().to_string())?;
        let mut state = HashMap::new();
        for e in std::fs::read_dir(&dir).context("read log dir")? {
            let p = e?.path();
            if p.extension().and_then(|s| s.to_str()) != Some("jsonl") {
                continue;
            }
            let Some(id) = p.file_stem().and_then(|s| s.to_str()) else { continue };
            let mut log = Log { next_seq: 1, by_key: HashMap::new() };
            for line in std::fs::read(&p).context("read log")?.split(|b| *b == b'\n') {
                if line.is_empty() {
                    continue;
                }
                if let Ok(en) = serde_json::from_slice::<Entry>(line) {
                    log.next_seq = log.next_seq.max(en.seq + 1);
                    log.by_key.insert((en.session.clone(), en.idx), en);
                }
            }
            state.insert(id.to_string(), log);
        }
        Ok(TrajLog { dir, state: Mutex::new(state) })
    }

    fn path(&self, sandbox: &str) -> PathBuf {
        // Sandbox ids are generated by the platform (never user text).
        self.dir.join(format!("{sandbox}.jsonl"))
    }

    /// Record a completed operation; returns its sequence number. Appended and
    /// flushed to local disk before returning (V4: "persistently recording").
    pub fn record(&self, sandbox: &str, entry: Entry) -> Result<u64> {
        let mut st = self.state.lock().unwrap();
        let log = st.entry(sandbox.to_string()).or_insert_with(|| Log { next_seq: 1, by_key: HashMap::new() });
        let seq = log.next_seq;
        let mut entry = entry;
        entry.seq = seq;
        log.next_seq += 1;
        log.by_key.insert((entry.session.clone(), entry.idx), entry.clone());
        let line = serde_json::to_vec(&entry).context("serialize entry")?;
        use std::io::Write;
        let mut f = std::fs::OpenOptions::new().create(true).append(true).open(self.path(sandbox))?;
        f.write_all(&line)?;
        f.write_all(b"\n")?;
        f.sync_data().context("fsync trajectory")?;
        Ok(seq)
    }

    /// Fast-forward lookup: the completed entry for (session, idx), if any.
    pub fn lookup(&self, sandbox: &str, session: &str, idx: u64) -> Option<Entry> {
        let st = self.state.lock().unwrap();
        let log = st.get(sandbox)?;
        log.by_key.get(&(session.to_string(), idx)).cloned()
    }

    /// Compare a re-issued operation against the recorded one.
    pub fn replay(
        &self,
        sandbox: &str,
        session: &str,
        idx: u64,
        op: &str,
        params: &serde_json::Value,
    ) -> Replay {
        match self.lookup(sandbox, session, idx) {
            None => Replay::Miss,
            Some(e) if e.op == op && e.params == *params => Replay::Hit(e),
            Some(e) => Replay::Diverged(e),
        }
    }

    /// Provenance query: all entries of a sandbox in global order, optionally
    /// filtered by session and/or op.
    pub fn query(&self, sandbox: &str, session: Option<&str>, op: Option<&str>) -> Vec<Entry> {
        let st = self.state.lock().unwrap();
        let Some(log) = st.get(sandbox) else { return vec![] };
        let mut v: Vec<Entry> = log
            .by_key
            .values()
            .filter(|e| session.is_none_or(|s| e.session == s) && op.is_none_or(|o| e.op == o))
            .cloned()
            .collect();
        v.sort_by_key(|e| e.seq);
        v
    }

    pub fn sandboxes(&self) -> Vec<String> {
        self.state.lock().unwrap().keys().cloned().collect()
    }
}

#[derive(Debug, Clone)]
pub enum Replay {
    /// No entry for this (session, idx): execute and record.
    Miss,
    /// Completed entry with identical op+params: return cached result.
    Hit(Entry),
    /// Same identity, different op/params: the client's new trajectory
    /// diverges from the recorded one; surfaced, never silently replayed.
    Diverged(Entry),
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn entry(session: &str, idx: u64, op: &str, params: serde_json::Value, result: serde_json::Value) -> Entry {
        Entry { seq: 0, ts_ms: 0, user: "u1".into(), session: session.into(), idx, op: op.into(), params, result }
    }

    #[test]
    fn entries_are_ordered_and_globally_sequenced() {
        let d = tempfile::tempdir().unwrap();
        let t = TrajLog::open(d.path()).unwrap();
        let a = t.record("sbx", entry("s", 0, "exec", json!("a"), json!(1))).unwrap();
        let b = t.record("sbx", entry("s", 1, "exec", json!("b"), json!(2))).unwrap();
        let c = t.record("sbx", entry("t", 0, "exec", json!("c"), json!(3))).unwrap();
        assert!((a, b, c) == (1, 2, 3));
        let q = t.query("sbx", None, None);
        assert_eq!(q.iter().map(|e| e.seq).collect::<Vec<_>>(), vec![1, 2, 3]);
        assert_eq!(t.query("sbx", Some("t"), None).len(), 1);
        assert_eq!(t.query("sbx", None, Some("exec")).len(), 3);
        assert_eq!(t.query("sbx", None, Some("read_file")).len(), 0);
    }

    #[test]
    fn fast_forward_replays_identical_and_flags_divergence() {
        let d = tempfile::tempdir().unwrap();
        let t = TrajLog::open(d.path()).unwrap();
        t.record("sbx", entry("s", 0, "exec", json!("echo x >> f"), json!({"stdout": "", "code": 0}))).unwrap();
        match t.replay("sbx", "s", 0, "exec", &json!("echo x >> f")) {
            Replay::Hit(e) => assert_eq!(e.result["code"], 0),
            other => panic!("{other:?}"),
        }
        assert!(matches!(t.replay("sbx", "s", 0, "exec", &json!("echo y >> f")), Replay::Diverged(_)));
        assert!(matches!(t.replay("sbx", "s", 1, "exec", &json!("echo x >> f")), Replay::Miss));
        assert!(matches!(t.replay("other", "s", 0, "exec", &json!("echo x >> f")), Replay::Miss));
    }

    #[test]
    fn log_survives_restart_and_keeps_ordering() {
        let d = tempfile::tempdir().unwrap();
        {
            let t = TrajLog::open(d.path()).unwrap();
            t.record("sbx", entry("s", 0, "exec", json!("one"), json!(null))).unwrap();
            t.record("sbx", entry("s", 1, "exec", json!("two"), json!(null))).unwrap();
        }
        let t = TrajLog::open(d.path()).unwrap();
        assert!(matches!(t.replay("sbx", "s", 1, "exec", &json!("two")), Replay::Hit(_)));
        // Ordering continues from the reloaded max seq.
        assert_eq!(t.record("sbx", entry("s", 2, "exec", json!("three"), json!(null))).unwrap(), 3);
    }

    #[test]
    fn entries_recover_even_if_the_in_memory_cache_is_lost() {
        // Oracle for durability: the file on disk is the source of truth.
        let d = tempfile::tempdir().unwrap();
        {
            let t = TrajLog::open(d.path()).unwrap();
            t.record("sbx", entry("s", 0, "exec", json!("persist"), json!({"ok": true}))).unwrap();
        }
        let raw = std::fs::read_to_string(d.path().join("sbx.jsonl")).unwrap();
        assert!(raw.contains("persist"), "entry must be on disk, got: {raw}");
    }
}
