[package]
name = "dsec-edge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dsec-rpc.workspace = true
dsec-trajlog.workspace = true
dsec-watcher.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile.workspace = true
dsec-aether.workspace = true
